export const sampleUsers = [
  {
    userType: "player",
    userId: "player001",
    password: "password123",
    name: "John Doe",
    nickname: "Johnny",
    email: "john.doe@example.com",
    school: "Springfield High",
    studentId: "S12345",
    positions: ["Forward"],
    backNumber: "10",
  },
  {
    userType: "coach",
    userId: "coach001",
    password: "password123",
    name: "Jane Smith",
    nickname: "Coach Jane",
    email: "jane.smith@example.com",
    school: "Springfield High",
    studentId: null,
    positions: ["Head Coach"],
    backNumber: null,
  },
  {
    userType: "external",
    userId: "external001",
    password: "password123",
    name: "Bob Johnson",
    nickname: "Bobby",
    email: "bob.johnson@example.com",
    school: null,
    studentId: null,
    positions: ["Scout"],
    backNumber: null,
  },
  {
    userType: "player",
    userId: "player002",
    password: "password123",
    name: "Alice Williams",
    nickname: "Ali",
    email: "alice.williams@example.com",
    school: "Riverside Academy",
    studentId: "R12345",
    positions: ["Goalkeeper"],
    backNumber: "1",
  },
  {
    userType: "coach",
    userId: "coach002",
    password: "password123",
    name: "Tom Brown",
    nickname: "Tommy",
    email: "tom.brown@example.com",
    school: "Riverside Academy",
    studentId: null,
    positions: ["Assistant Coach"],
    backNumber: null,
  },
  {
    userType: "player",
    userId: "player003",
    password: "password123",
    name: "Emily Davis",
    nickname: "Em",
    email: "emily.davis@example.com",
    school: "Hillcrest School",
    studentId: "H12345",
    positions: ["Midfielder"],
    backNumber: "8",
  },
  {
    userType: "external",
    userId: "external002",
    password: "password123",
    name: "Charlie Brown",
    nickname: "Chuck",
    email: "charlie.brown@example.com",
    school: null,
    studentId: null,
    positions: ["Analyst"],
    backNumber: null,
  },
  {
    userType: "player",
    userId: "player004",
    password: "password123",
    name: "Sophia Wilson",
    nickname: "Sophie",
    email: "sophia.wilson@example.com",
    school: "Greenfield School",
    studentId: "G12345",
    positions: ["Defender"],
    backNumber: "5",
  },
  {
    userType: "coach",
    userId: "coach003",
    password: "password123",
    name: "Daniel Lee",
    nickname: "Danny",
    email: "daniel.lee@example.com",
    school: "Greenfield School",
    studentId: null,
    positions: ["Goalkeeper Coach"],
    backNumber: null,
  },
  {
    userType: "player",
    userId: "player005",
    password: "password123",
    name: "Olivia Martinez",
    nickname: "Liv",
    email: "olivia.martinez@example.com",
    school: "Sunset High",
    studentId: "S67890",
    positions: ["Striker"],
    backNumber: "9",
  },
  {
    userType: "external",
    userId: "external003",
    password: "password123",
    name: "David White",
    nickname: "Dave",
    email: "david.white@example.com",
    school: null,
    studentId: null,
    positions: ["Consultant"],
    backNumber: null,
  },
];
